server:
  port: 29000 # 端口号
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
spring:
  application:
    name: newbee-mall-cloud-user-service # 服务名称
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.75.191:8848 # Nacos地址
        username: naocs # Nacos登录用户名
        password: nacos # Nacos登录密码
  # datasource config (MySQL)
  datasource:
    name: newbee-mall-cloud-user-datasource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/newbee_mall_cloud_user_db?useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=utf8&autoReconnect=true&useSSL=false&allowMultiQueries=true&serverTimezone=PRC
    username: root
    password: root
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 60000
      pool-name: hikariCP
      max-lifetime: 600000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  ##Redis 配置
  redis:
    database: 13 # Redis数据库索引（默认为0）
    host: 101.42.172.206 # Redis服务器地址
    port: 6379 # Redis服务器连接端口
    password: LXL521521521 # Redis服务器连接密码
    jedis:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接
    timeout: 5000 # 连接超时时间（毫秒）
# mybatis的配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

